version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    command: npm run start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4200:4200'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev api
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    # restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - mongo_db:/data
    ports:
      - '27017:27017'
      
  redis:
    image: redis
    container_name: redis_db
    ports:
      - "6379:6379"
    env_file:
      - ./server/.env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS --save 60 1 --appendonly yes"
    volumes:
      - redis_data:/data
  
  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-insight
    ports:
      - "8001:8001"
    depends_on:
      - redis
      
volumes:
  mongo_db:
    driver: local

  redis_data:
    driver: local